// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs6pn-s1ienZviCkOvx2a6bZbSVUdJyZQ',
    appId: '1:230075753481:web:1cd7409060ec977f62c4d8',
    messagingSenderId: '230075753481',
    projectId: 'skillcampus-4165c',
    authDomain: 'skillcampus-4165c.firebaseapp.com',
    databaseURL: 'https://skillcampus-4165c-default-rtdb.firebaseio.com',
    storageBucket: 'skillcampus-4165c.firebasestorage.app',
    measurementId: 'G-M8P8MHH1BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzwCJ00rdJMjcm1t4f5pCLF4sLwxQhvTU',
    appId: '1:230075753481:android:22c5f46ecef24b7a62c4d8',
    messagingSenderId: '230075753481',
    projectId: 'skillcampus-4165c',
    databaseURL: 'https://skillcampus-4165c-default-rtdb.firebaseio.com',
    storageBucket: 'skillcampus-4165c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-jk6Hlu7uRtT6bg7m0zaDGxFLxAcDPnE',
    appId: '1:230075753481:ios:3f1479fbe1ee529462c4d8',
    messagingSenderId: '230075753481',
    projectId: 'skillcampus-4165c',
    databaseURL: 'https://skillcampus-4165c-default-rtdb.firebaseio.com',
    storageBucket: 'skillcampus-4165c.firebasestorage.app',
    iosBundleId: 'br.luhstark.skillcampus',
  );
}
